# Generated by Django 5.0.2 on 2024-02-17 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='mentions',
            field=models.ManyToManyField(related_name='mentioned_in_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
