# Generated by Django 5.0.2 on 2024-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='total_reposts',
            field=models.IntegerField(default=0),
        ),
    ]
