# Generated by Django 5.0.2 on 2024-02-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tweet_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='mentions',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentioned_in_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_media',
            field=models.ManyToManyField(blank=True, null=True, to='user.t_media'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_tags',
            field=models.ManyToManyField(blank=True, null=True, to='user.tags'),
        ),
    ]
