# Generated by Django 5.0.2 on 2024-02-20 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_tweet_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='views',
            field=models.ManyToManyField(related_name='viewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
