# Generated by Django 5.0.2 on 2024-02-14 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email_otp_user_email_verified_user_phone_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='tweets')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='verified_account',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500, null=True)),
                ('tweet_type', models.IntegerField(choices=[(0, 'Message'), (1, 'Media'), (2, 'Poll')], default=0)),
                ('reply_by', models.IntegerField(choices=[(0, 'Everyone'), (1, 'Accounts you follow'), (2, 'Verified'), (3, 'Only accounts mention')], default=0)),
                ('active_status', models.BooleanField(default=True)),
                ('schedule_tym', models.DateTimeField(blank=True, null=True)),
                ('end_tym', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_type', models.IntegerField(choices=[(0, 'Message'), (1, 'Media')], default=0)),
                ('active_status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tweet')),
            ],
        ),
    ]
