# Generated by Django 5.0.2 on 2024-02-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
