# Generated by Django 5.0.2 on 2024-02-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tags_created_on_tags_used_times_user_bg_imgg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_media',
            field=models.ManyToManyField(blank=True, null=True, to='user.t_media'),
        ),
    ]
