# Generated by Django 5.0.2 on 2024-02-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
