# Generated by Django 5.0.2 on 2024-02-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_header_photo_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
