# Generated by Django 5.0.2 on 2024-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='msg',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
