# Generated by Django 5.0.2 on 2024-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_tweet_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='used_times',
            field=models.IntegerField(default=1),
        ),
    ]
